

fprintf(['  _______   _______   _______   _______   ',...
    '\n |  ___  | |  ___  | |  ___  | |  ___  |  ______ ',...
    '\n | |   |_| | |   | | | |   | | | |   | | |  ____|',...
    '\n | |       | |   | | | |___| | | |___| | | |____ ',...
    '\n | |    _  | |   | | |  _____| |  _____| |____  |',...
    '\n | |___| | | |___| | | |       | |        ____| |',...
    '\n |_______| |_______| |_|       |_|       |______|',...
    '\n',...
    '\n',...
    '\nA Toolkit for Computing Constrained Optimal Policy Projections',...
    '\nVersion 1.0',...
    '\n',...
    '\nde Groot, Mazelis, Motto, Ristiniemi',...
    '\nECB Working Paper 2021 No. xxx',...
    '\n',...
    '\n',...
    '\nCopyright (C) de Groot, Mazelis, Motto, Ristiniemi',...
    '\n',...
    '\nThis program is free software: you can redistribute it and/or modify',...
    '\nit under the terms of the GNU General Public License as published by',...
    '\nthe Free Software Foundation,  version 3 of the License.',...
    '\n',...
    '\nThis program is distributed in the hope that it will be useful,',...
    '\nbut WITHOUT ANY WARRANTY; without even the implied warranty of',...
    '\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the',...
    '\nGNU General Public License for more details.',...
    '\n',...
    '\nYou should have received a copy of the GNU General Public License',...
    '\nalong with this program.  If not, see <https://www.gnu.org/licenses/>.',...
    '\n',...
    '\n--------------------------------------------------------------'...,
    '\n',...
    '\n',...
    ])
pause(2);

